### ISSUE TITLE
Identifier System for GNC codes

### ISSUE THREAD

**Issue by ahatherly** [HL7-UK/System-Identifiers#3]
Can we add an identifier for GNC (General National Codes) codes as used in the ODS files (specifially **egpcur**) here to identify general practitioners?: https://digital.nhs.uk/services/organisation-data-service/data-downloads/gp-and-gp-practice-related-data

**Comment by ahatherly** [comment]
FYI - NHS Digital have advised that the URI should be: **https://fhir.hl7.org.uk/Id/gnc-codes**

**Comment by Dunmail** [comment]
Thanks Adam - GNC code added (https://github.com/HL7-UK/System-Identifiers/commit/b914985a02048a7f14de96aff67fc2332592e9cd)
